name: formatting_check
run-name: Check code formatting
on: push
jobs:
  formatting_check:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      uses: actions/checkout@v3

    - name: Run formatting check
      uses: paolorechia/pox@v1.0.1
      with:
        tox_env: format_check

env:
  PIP_INDEX_URL: https://pypi-wayback-449168051873.europe-west3.run.app/2023-12-22
  UV_INDEX_URL: https://pypi-wayback-449168051873.europe-west3.run.app/2023-12-22
